### ISSUE TITLE
how to test one picture

### ISSUE THREAD

**Issue by ZhouKuai2019** [xavysp/DexiNed#1]
How to configure the run_model.py，parser.add_argument('--dataset_dir',default=None,type=str)
where can i put the one picture to test? Thank you very much!

**Comment by ZhouKuai2019** [comment]
by the way what is The python version used

**Comment by xavysp** [comment]
> How to configure the run_model.py，parser.add_argument('--dataset_dir',default=None,type=str)
> where can i put the one picture to test? Thank you very much!

Hi @ZhouKuai2019  right now DexiNed is set for a single or one picture. You know, before running, you should download the checkpoint and save it into DexiNed folder (DexiNed/checkpoints/DXN_BIPED/train/"the checkpoint"). The images or image for testing have to be into the "data" folder (DexiNed/data/"image"), right now there is "lena_std.tif", you can test that one or change by other image or images.

Cheers,

Xavier

**Comment by xavysp** [comment]
> by the way what is the python version used

Hi, sorry  I have just updated the python version, by the way, is Python 3.7

Xavier

**Comment by ZhouKuai2019** [comment]
Thanks for your help. Your answer solved my problem！With best wishes!

**Comment by ZhouKuai2019** [comment]
Hello, when I extracted the edge of the picture of the hole shaft, I found that the average and fusion would produce redundant details, may I ask which method can I achieve output1 to output6

**Comment by xavysp** [comment]
> Hello, when I extracted the edge of the picture of the hole shaft, I found that the average and fusion would produce redundant details, may I ask which method can I achieve output1 to output6

Hi could you share with me the predicted edge-map?
as this is edge detection this model try to detect as many edges as possible

**Comment by ZhouKuai2019** [comment]
> > Hello, when I extracted the edge of the picture of the hole shaft, I found that the average and fusion would produce redundant details, may I ask which method can I achieve output1 to output6
> 
> Hi could you share with me the predicted edge-map?
> as this is edge detection this model try to detect as many edges as possible

OK,how can i share with you the edge-map, can i have your email?

**Comment by xavysp** [comment]
> > > Hello, when I extracted the edge of the picture of the hole shaft, I found that the average and fusion would produce redundant details, may I ask which method can I achieve output1 to output6
> > 
> > 
> > Hi could you share with me the predicted edge-map?
> > as this is edge detection this model try to detect as many edges as possible
> 
> OK,how can i share with you the edge-map, can i have your email?

Sure you can have in my pofile
