### ISSUE TITLE
The code of the fifth block seems to be inconsistent with the network structure of the fifth block

### ISSUE THREAD

**Issue by liuxingyu123** [xavysp/DexiNed#105]
`# Block 5
        block_5_pre_dense = self.pre_dense_5(block_4_down)  # block_5_pre_dense_512 +block_4_down
        block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
        block_5_add = block_5 + block_4_side`

**Comment by liuxingyu123** [comment]
hi，I see that the code written using tensorflow is consistent with the framework in the paper, but it seems that pytorch directly uses the third max-pooling without adding the first and second max-pooling
pytorch：`# Block 5
        block_5_pre_dense = self.pre_dense_5(block_4_down)  # block_5_pre_dense_512 +block_4_down
        block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
        block_5_add = block_5 + block_4_side`
tf：`# Block 5
        block_5_pre_dense_512 = self.pre_dense_5_0(block_4_pre_dense_256)
        block_5_pre_dense = self.pre_dense_5(block_5_pre_dense_512 + block_4_down )
        block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
        block_5_add = block_5 + block_4_side`

**Comment by liuxingyu123** [comment]
hi，I see that the code written using tensorflow is consistent with the framework in the paper, but it seems that pytorch directly uses the third max-pooling without adding the first and second max-pooling
pytorch：
```
# Block 5
        
block_5_pre_dense = self.pre_dense_5(block_4_down)      # block_5_pre_dense_512 +block_4_down
        
block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
        
block_5_add = block_5 + block_4_side
````

tf：

```
# Block 5
        
block_5_pre_dense_512 = self.pre_dense_5_0(block_4_pre_dense_256)
        
block_5_pre_dense = self.pre_dense_5(block_5_pre_dense_512 + block_4_down )
        
block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
        
block_5_add = block_5 + block_4_side
```

**Comment by xavysp** [comment]
> hi，I see that the code written using tensorflow is consistent with the framework in the paper, but it seems that pytorch directly uses the third max-pooling without adding the first and second max-pooling pytorch：
> 
> ```
> # Block 5
>         
> block_5_pre_dense = self.pre_dense_5(block_4_down)      # block_5_pre_dense_512 +block_4_down
>         
> block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
>         
> block_5_add = block_5 + block_4_side
> ```
> 
> tf：
> 
> ```
> # Block 5
>         
> block_5_pre_dense_512 = self.pre_dense_5_0(block_4_pre_dense_256)
>         
> block_5_pre_dense = self.pre_dense_5(block_5_pre_dense_512 + block_4_down )
>         
> block_5, _ = self.dblock_5([block_4_add, block_5_pre_dense])
>         
> block_5_add = block_5 + block_4_side
> ```

Hi @liuxingyu123  thank you for your wise review. Actually, the last version of DexiNed is the code in PyTorch. The version for TF2 will take longer than I expected, I am super busy, but you can see the model (block5) correction in the TF2 model.

If you find more inconsistencies please let me know and I will approach in the coming months.

Cheers,

Xavier

**Comment by liuxingyu123** [comment]
fine,thank you for your reply.
