### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by pu-1** [xavysp/DexiNed#113]
HI I would like to know how the result of such a picture can be turned into a format that can be evaluated or can you share your evaluation code?
![image](https://user-images.githubusercontent.com/63955909/175511336-f55605ae-be53-4c7b-a6d4-a243d4abebd4.png)

**Comment by xavysp** [comment]
Hi, welcome on board.
 Did you checked the issue  32? (Evaluation index of edge detection #32) or your question is not related to 32 is it?
Cheers.

**Comment by pu-1** [comment]
sry it's my bad.
