### ISSUE TITLE
About args.double_img

### ISSUE THREAD

**Issue by Twsaiae** [xavysp/DexiNed#119]
1、if args.double_img is True, are the result images of fused better than the result images of avg?
2、if args.double_img is False, are the result images of fused better than the result images of avg?
3、if args.double_img is False, are the resulting images in the fused folder still valuable?

**Comment by Twsaiae** [comment]
> Hi, thanks for interesting on DexiNed, there is not much difference, but I have not investigated properly, that is why I didn't report this part in the Paper. It could be great compare this one with the HED multiscale testing.

All right... So if args.double_img is set to False, it is the original appearance of your demo code, Do you think the result pictures in the avg folder are better, or the pictures in fused are better? In other words, what do you think of the results in these two folders?

**Comment by Twsaiae** [comment]
All I know is that avg is the average of 7 result tensors, and fused doesn't give it the result of the second picture, so it's only the result of the seventh tensor, but it seems that the result of fused is more refreshing.....

**Comment by Twsaiae** [comment]
Which results were used in those papers with code competitions?

**Comment by xavysp** [comment]
Hi,
 In the paper, if the comparison does not show DexiNed-a it means that DexiNed result is from the fused edge-map.
With respect to which one is better it depends, quantitatively DexiNed-a is better but qualitatively, perceptually, DexiNed-f is better. We should check the results in other tasks like image segmentation.  The fused is predicted with in CNN layer operation.
