### ISSUE TITLE
Inference mode is available?

### ISSUE THREAD

**Issue by HripsimeS** [xavysp/DexiNed#123]
@xavysp @edgarriba @stephenwithav  Hello!!!

I tried the test mode and the results look great. So in your repository you have train and test modes, in both cases edge-maps or labels are availible. But does DexiNed also work on inference mode? I mean by using a trained model in this case **10_model.pth** file can we upload images and get their edges predictions without having their true labels.

Look forward to hearing from you!

**Comment by edgarriba** [comment]
@HripsimeS this is the research repository -- we are actually porting for a more production phase into kornia
https://github.com/kornia/kornia/pull/1483
