### ISSUE TITLE
GT

### ISSUE THREAD

**Issue by Scott-che** [xavysp/DexiNed#124]
![6](https://user-images.githubusercontent.com/67545227/199390927-ae8351f2-e372-43f5-9e1d-157a4e084a65.PNG)
HI,I want to ask what the work is here mean?
And how to decise the value like label[label > 0.1] +=0.2

**Comment by xavysp** [comment]
Well this is an empirical evaluation, so as brind has many GTs, they are mixed, it will smooth the neighbor pixels so we just add 0.2. If we set like gt>0.= 1, the predicted edgemaps will be a little more  thick.  But you can try.
