### ISSUE TITLE
Will you release  a Pytorch version?

### ISSUE THREAD

**Issue by Thebluebluesky** [xavysp/DexiNed#2]
thanks

**Comment by xavysp** [comment]
> thanks

Hi thanks for the interest in DexiNed. Right now I am too busy, but I have a draft. Give a couple of months. Anf I hope so.

**Comment by xavysp** [comment]
Hi @Thebluebluesky 
we have finished with DexiNed implementation in PyTorch, please check it [DexiNed-Pytorch](https://github.com/xavysp/DexiNed/tree/master/DexiNed-Pytorch).

By the way, I am starting in Pytorch 

Cheers!

xavier

**Comment by cainiaoqiuzhu** [comment]
> Hi @Thebluebluesky
> we have finished with DexiNed implementation in PyTorch, please check it [DexiNed-Pytorch](https://github.com/xavysp/DexiNed/tree/master/DexiNed-Pytorch).
> 
> By the way, I am starting in Pytorch
> 
> Cheers!
> 
> xavier

Why do you delete the Pytorch Version?
