### ISSUE TITLE
how to annotate my own images？

### ISSUE THREAD

**Issue by nywang2019** [xavysp/DexiNed#23]
hi@xavysp, i have some questions in #22 waiting for your help.  here is a new question, i want to use my own images as train and validation set, could u tell me how to annotate images as you do? thanks.

**Comment by xavysp** [comment]
> hi@xavysp, i have some questions in #22 waiting for your help. here is a new question, i want to use my own images as train and validation set, could u tell me how to annotate images as you do? thanks.

Hi sorry, I will answer later the #22 but for the annotation, I did on LabelBox. So you can do it there.

Xavier

**Comment by nywang2019** [comment]
@xavysp thank u verymuch。

**Comment by nywang2019** [comment]
i know labelbox,  but would you please tell me how did you generate the edge map?   actually I know nothing about it, I will appreciate if you can teach me some details about how to generate edge maps. how much time did it take for your 250 pics?

**Comment by xavysp** [comment]
I think I don't understand the question
if you mean annotation yes you should do manually, at that time, I used LabelBox it did not have most of the tools that you can find now, maybe your annotation will be improved now. Depending on how many edges you can find on your image it will take 40 min per image, but it depends no your data.

Hope I answered your question

**Comment by nywang2019** [comment]
i got it. yes,  u answered my question.  40 min per image manually, that is really time-consuming. you did a good work.
