### ISSUE TITLE
TFlite conversion.

### ISSUE THREAD

**Issue by LuanBaviloni** [xavysp/DexiNed#24]
I tried to convert it for a TFLite version. But the FusedBatchNorm layers are not being converted. Is there a solution for this?

**Comment by xavysp** [comment]
> I tried to convert it for a TFLite version. But the FusedBatchNorm layers is not being converted. Is there a solution for this?

well right now we are preparing DexiNed in the base CNN models of TF like nn.conv2d, I think this will help us. Maybe at the end of this week, this version will be ready

**Comment by ranajit1996** [comment]
Size of TFLite model is about 34mb!! Any plan to optimize Dexined for mobile devices?

**Comment by umeshsati54** [comment]
> Size of TFLite model is about 34mb!! Any plan to optimize Dexined for mobile devices?

can you please share your TFLite model?

**Comment by LuanBaviloni** [comment]
> Size of TFLite model is about 34mb!! Any plan to optimize Dexined for mobile devices?

Are you getting  good results with your TFLite model?
