### ISSUE TITLE
I trained the model, but the results are not as good as the paper's

### ISSUE THREAD

**Issue by nywang2019** [xavysp/DexiNed#25]
Hi @xavysp I trained the model using NVIDIA P100 Pascal 12G,  it does not work when batchsize=8, so I set the train and validation batch size=4. another para modification is val_interval=300 (default=30). 
The total training time is 71.5h (including 1.5 for data augmentation)
Max-iteration:150000
I tested Lena, here is the result. it is not as good as the paper's.  is it because of batch size? 
 
![lena_std](https://user-images.githubusercontent.com/55544699/83148484-04577d00-a0c7-11ea-86bc-561c4e104ccf.png)
pred-a of mine
![lena_std_train1](https://user-images.githubusercontent.com/55544699/83149196-d58dd680-a0c7-11ea-9522-ed31e7474b08.png)
pred-a of the author's train1
![lena_std_train2](https://user-images.githubusercontent.com/55544699/83149444-12f26400-a0c8-11ea-8424-d1b1e4dd1ae0.png)
pred-a of the author's train2
![lena_std](https://user-images.githubusercontent.com/55544699/83148507-0d484e80-a0c7-11ea-8783-b73ebcb79628.png)
pred-f of mine
![lena_std_train1](https://user-images.githubusercontent.com/55544699/83149487-256c9d80-a0c8-11ea-9ffe-44faade041ff.png)
pred-f of the author's train1
![lena_std_train2](https://user-images.githubusercontent.com/55544699/83149515-2dc4d880-a0c8-11ea-8474-7f4f5f606564.png)
pred-f of the author's train2

here are my parameter details:
    parser = argparse.ArgumentParser(description='Basic details to run HED')
    # dataset config
    parser.add_argument('--train_dataset', default='BIPED', choices=['BIPED','BSDS'])
    parser.add_argument('--test_dataset', default='CLASSIC', choices=['BIPED', 'BSDS','MULTICUE','NYUD','PASCAL','CID','DCD'])
    parser.add_argument('--dataset_dir',default='./MBIPED/dataset/',type=str) # default:'/opt/dataset/'
    parser.add_argument('--dataset_augmented', default=True,type=bool)
    parser.add_argument('--train_list',default='train_rgb.lst', type=str) # BSDS train_pair.lst, SSMIHD train_rgb_pair.lst/train_rgbn_pair.lst
    parser.add_argument('--test_list', default='test_rgb.lst',type=str) # for NYUD&BSDS:test_pair.lst, ssmihd: msi_test.lst/vis_test.lst
    parser.add_argument('--trained_model_dir', default='train_1',type=str) # 'trainV2_RN'
    # SSMIHD_RGBN msi_valid_list.txt and msi_test_list.txt is for unified test
    parser.add_argument('--use_nir', default=False, type=bool)
    parser.add_argument('--use_dataset', default=False, type=bool) # test: dataset TRUE single image FALSE
    # model config
    parser.add_argument('--model_state', default='train', choices=['train','test','None']) # always in None
    parser.add_argument('--model_name', default='DXN',choices=['DXN','XCP','None'])
    parser.add_argument('--use_v1', default=False,type=bool)
    parser.add_argument('--model_purpose', default='edges',choices=['edges','restoration','None'])
    parser.add_argument('--batch_size_train',default=1,type=int) # default:8
    parser.add_argument('--batch_size_val',default=1, type=int) # default:8
    parser.add_argument('--batch_size_test',default=1,type=int)
    parser.add_argument('--checkpoint_dir', default='checkpoints',type=str)
    parser.add_argument('--logs_dir', default='logs',type=str)
    parser.add_argument('--learning_rate',default=1e-4, type=float) # 1e-4=0.0001
    parser.add_argument('--lr_scheduler',default=None,choices=[None,'asce','desc']) # check here
    parser.add_argument('--learning_rate_decay', default=0.1,type=float)
    parser.add_argument('--weight_decay', default=0.0002, type=float)
    parser.add_argument('--model_weights_path', default='vgg16_.npy')
    parser.add_argument('--train_split', default=0.9, type=float) # default 0.8
    parser.add_argument('--max_iterations', default=150000, type=int) # 100000
    parser.add_argument('--learning_decay_interval',default=25000, type=int) # 25000
    parser.add_argument('--loss_weights', default=1.0, type=float)
    parser.add_argument('--save_interval', default=50000, type=int)  # 50000
    parser.add_argument('--val_interval', default=10, type=int) # default: 30
    parser.add_argument('--use_subpixel', default=None, type=bool)  # None=upsampling with transp conv
    parser.add_argument('--deep_supervision', default=True, type= bool)
    parser.add_argument('--target_regression',default=True, type=bool) # true
    parser.add_argument('--mean_pixel_values', default=[103.939,116.779,123.68, 137.86], type=float)# [103.939,116.779,123.68]
    # for Nir pixels mean [103.939,116.779,123.68, 137.86]
    parser.add_argument('--channel_swap', default=[2,1,0], type=int)
    parser.add_argument('--gpu-limit',default=1.0, type= float, )
    parser.add_argument('--use_trained_model', default=True,type=bool) # for vvg16
    parser.add_argument('--use_previous_trained', default=False, type=bool)
    # image configuration
    parser.add_argument('--image_width', default=1280, type=int) # 480 NYUD=560 BIPED=1280 default 400 other 448
    parser.add_argument('--image_height', default=720, type=int) # 480 for NYUD 425 BIPED=720 default 400
    parser.add_argument('--n_channels', default=3, type=int) # last ssmihd_xcp trained in 512
    # test config
    parser.add_argument('--test_snapshot', default=149736, type=int) #  BIPED: 149736 BSDS:101179
    #DexiNedv1=149736,DexiNedv2=149999
    parser.add_argument('--testing_threshold', default=0.0, type=float)
    parser.add_argument('--base_dir_results',default=None,type=str) # default: './results'

**Comment by nywang2019** [comment]
by the way, what is the difference between the two provided pretrained models, namely train1 and train2?   the results of them are different from each other. it seems train1's results are better.

**Comment by xavysp** [comment]
> Hi @xavysp I trained the model using NVIDIA P100 Pascal 12G, it does not work when batchsize=8, so I set the train and validation batch size=4. another para modification is val_interval=300 (default=30).
> The total training time is 71.5h (including 1.5 for data augmentation)
> Max-iteration:150000
> I tested Lena, here is the result. it is not as good as the paper's. is it because of batch size?
> 
> ![lena_std](https://user-images.githubusercontent.com/55544699/83148484-04577d00-a0c7-11ea-86bc-561c4e104ccf.png)
> pred-a of mine
> ![lena_std_train1](https://user-images.githubusercontent.com/55544699/83149196-d58dd680-a0c7-11ea-9522-ed31e7474b08.png)
> pred-a of the author's train1
> ![lena_std_train2](https://user-images.githubusercontent.com/55544699/83149444-12f26400-a0c8-11ea-8424-d1b1e4dd1ae0.png)
> pred-a of the author's train2
> ![lena_std](https://user-images.githubusercontent.com/55544699/83148507-0d484e80-a0c7-11ea-8783-b73ebcb79628.png)
> pred-f of mine
> ![lena_std_train1](https://user-images.githubusercontent.com/55544699/83149487-256c9d80-a0c8-11ea-9ffe-44faade041ff.png)
> pred-f of the author's train1
> ![lena_std_train2](https://user-images.githubusercontent.com/55544699/83149515-2dc4d880-a0c8-11ea-8474-7f4f5f606564.png)
> pred-f of the author's train2
> 
> here are my parameter details:
> parser = argparse.ArgumentParser(description='Basic details to run HED')
> # dataset config
> parser.add_argument('--train_dataset', default='BIPED', choices=['BIPED','BSDS'])
> parser.add_argument('--test_dataset', default='CLASSIC', choices=['BIPED', 'BSDS','MULTICUE','NYUD','PASCAL','CID','DCD'])
> parser.add_argument('--dataset_dir',default='./MBIPED/dataset/',type=str) # default:'/opt/dataset/'
> parser.add_argument('--dataset_augmented', default=True,type=bool)
> parser.add_argument('--train_list',default='train_rgb.lst', type=str) # BSDS train_pair.lst, SSMIHD train_rgb_pair.lst/train_rgbn_pair.lst
> parser.add_argument('--test_list', default='test_rgb.lst',type=str) # for NYUD&BSDS:test_pair.lst, ssmihd: msi_test.lst/vis_test.lst
> parser.add_argument('--trained_model_dir', default='train_1',type=str) # 'trainV2_RN'
> # SSMIHD_RGBN msi_valid_list.txt and msi_test_list.txt is for unified test
> parser.add_argument('--use_nir', default=False, type=bool)
> parser.add_argument('--use_dataset', default=False, type=bool) # test: dataset TRUE single image FALSE
> # model config
> parser.add_argument('--model_state', default='train', choices=['train','test','None']) # always in None
> parser.add_argument('--model_name', default='DXN',choices=['DXN','XCP','None'])
> parser.add_argument('--use_v1', default=False,type=bool)
> parser.add_argument('--model_purpose', default='edges',choices=['edges','restoration','None'])
> parser.add_argument('--batch_size_train',default=1,type=int) # default:8
> parser.add_argument('--batch_size_val',default=1, type=int) # default:8
> parser.add_argument('--batch_size_test',default=1,type=int)
> parser.add_argument('--checkpoint_dir', default='checkpoints',type=str)
> parser.add_argument('--logs_dir', default='logs',type=str)
> parser.add_argument('--learning_rate',default=1e-4, type=float) # 1e-4=0.0001
> parser.add_argument('--lr_scheduler',default=None,choices=[None,'asce','desc']) # check here
> parser.add_argument('--learning_rate_decay', default=0.1,type=float)
> parser.add_argument('--weight_decay', default=0.0002, type=float)
> parser.add_argument('--model_weights_path', default='vgg16_.npy')
> parser.add_argument('--train_split', default=0.9, type=float) # default 0.8
> parser.add_argument('--max_iterations', default=150000, type=int) # 100000
> parser.add_argument('--learning_decay_interval',default=25000, type=int) # 25000
> parser.add_argument('--loss_weights', default=1.0, type=float)
> parser.add_argument('--save_interval', default=50000, type=int) # 50000
> parser.add_argument('--val_interval', default=10, type=int) # default: 30
> parser.add_argument('--use_subpixel', default=None, type=bool) # None=upsampling with transp conv
> parser.add_argument('--deep_supervision', default=True, type= bool)
> parser.add_argument('--target_regression',default=True, type=bool) # true
> parser.add_argument('--mean_pixel_values', default=[103.939,116.779,123.68, 137.86], type=float)# [103.939,116.779,123.68]
> # for Nir pixels mean [103.939,116.779,123.68, 137.86]
> parser.add_argument('--channel_swap', default=[2,1,0], type=int)
> parser.add_argument('--gpu-limit',default=1.0, type= float, )
> parser.add_argument('--use_trained_model', default=True,type=bool) # for vvg16
> parser.add_argument('--use_previous_trained', default=False, type=bool)
> # image configuration
> parser.add_argument('--image_width', default=1280, type=int) # 480 NYUD=560 BIPED=1280 default 400 other 448
> parser.add_argument('--image_height', default=720, type=int) # 480 for NYUD 425 BIPED=720 default 400
> parser.add_argument('--n_channels', default=3, type=int) # last ssmihd_xcp trained in 512
> # test config
> parser.add_argument('--test_snapshot', default=149736, type=int) # BIPED: 149736 BSDS:101179
> #DexiNedv1=149736,DexiNedv2=149999
> parser.add_argument('--testing_threshold', default=0.0, type=float)
> parser.add_argument('--base_dir_results',default=None,type=str) # default: './results'

Hi in the training stage you set the placeholder with (?,400,400,3) but in the testing, you should use the real image size or at least image width or height factor of 16. For lenna, for example, is 512x512.

With respect to the max iteration, if your batch is 4, the max iter should be the double of 150K.

**Comment by xavysp** [comment]
> by the way, what is the difference between the two provided pretrained models, namely train1 and train2? the results of them are different from each other. it seems train1's results are better.

The train1 is the model trained with the first version of BIPED, and the train2 is with the last version of BIPED. Quantitatively, train2 is better.

**Comment by nywang2019** [comment]
ok，i will retry
