### ISSUE TITLE
a tinny setting mistake between  run_model.py and dexined.py

### ISSUE THREAD

**Issue by nywang2019** [xavysp/DexiNed#28]
in run_model.py line56:  parser.add_argument('--use_subpixel', default=None, type=bool)  # None=upsampling with transp conv

but in dexined.py line316:             elif sub_pixel is None:         # Upsampling by bilinear interpolation

@xavysp I think  there is a conflict between each other.  line56 of run_model.py should be changed as follow:
 parser.add_argument('--use_subpixel', default=False, type=bool)  # False =upsampling with transp conv

**Comment by xavysp** [comment]
> in run_model.py line56: parser.add_argument('--use_subpixel', default=None, type=bool) # None=upsampling with transp conv
> 
> but in dexined.py line316: elif sub_pixel is None: # Upsampling by bilinear interpolation
> 
> @xavysp I think there is a conflict between each other. line56 of run_model.py should be changed as follow:
> parser.add_argument('--use_subpixel', default=False, type=bool) # False =upsampling with transp conv

Hi thanks, I thought I updated this part

**Comment by nywang2019** [comment]
you are welcome
