### ISSUE TITLE
Setting up DexiNed traied model

### ISSUE THREAD

**Issue by cliffyb824** [xavysp/DexiNed#31]
Hi,

I'm really new to this, but found your work very interesting. I wonder is it possible to set my own data as training set? How should I do that? My images are all jpg files.

BTW, is it possible to thinner the lines in the results?

One more question, what do the four folders (pred-a, pred-f, etc.) in the results folder stand for separate?

Thanks!!

**Comment by xavysp** [comment]
> Hi,
> 
> I'm really new to this, but found your work very interesting. I wonder is it possible to set my own data as training set? How should I do that? My images are all jpg files.

Hi thanks for interesting of DexiNed and welcome on board :) please tell me did check the closed issues like #6, #22 and #25  such issues could be very helpful.
By the way you can train any image even grayscale (but with three channels)

> 
> BTW, is it possible to thinner the lines in the results?
Yes, the easiest way is up-scaling your input image for example if they are 512x512 re-scaling with the factor of 2, but it will give you more edges. 
> 
> One more question, what do the four folders (pred-a, pred-f, etc.) in the results folder stand for separate?

please check those issues :) if later you have more questions I will be here.

Cheers
> 
> Thanks!!
