### ISSUE TITLE
How to init fusing conv layer

### ISSUE THREAD

**Issue by shkarupa-alex** [xavysp/DexiNed#34]
Here https://github.com/xavysp/DexiNed/blob/master/DexiNed-TF2/model.py#L241 you init fusing layer as 1/5, but actually there are 6-channel scales input.

Is it an issue?

**Comment by xavysp** [comment]
> Here https://github.com/xavysp/DexiNed/blob/master/DexiNed-TF2/model.py#L241 you init fusing layer as 1/5, but actually there are 6-channel scales input.
> 
> Is it an issue?

Hi, actually we could use 1/6(in hed is 1/N---1/5), but after using 1/N-1, we saw a slightly clearer edge-map from  DexiNed-f. That is why we used such constant init.
