### ISSUE TITLE
Bug in loading a previous trained checkpoint with custom checkpoint_dir

### ISSUE THREAD

**Issue by LuanBaviloni** [xavysp/DexiNed#35]
When use a different **checkpoint_dir** with **--use_previous_trained True**, run_model.py fails to load the checkpoint.

The problem is in **train.py**, line **50** :

`model_path = os.path.join('checkpoints',self.args.model_name+`

should be replace with:

` model_path = os.path.join(self.args.checkpoint_dir,self.args.model_name+`

**Comment by xavysp** [comment]
> model_path = os.path.join(self.args.checkpoint_dir,self.args.model_name+

Hi thanks, Done!
