### ISSUE TITLE
State of PyTorch version pretrained model?

### ISSUE THREAD

**Issue by xiankgx** [xavysp/DexiNed#37]
Hi, I see there is a checkpoint in the checkpoint folder within the DexiNed-Pytorch folder. May I know what is the status of this checkpoint? How is the performance of the PyTorch model in comparison to your TF2 model? 

I'm asking this because I'm seeing quite some mistakes in the code. I have made quite some changes to the code while trying to maintain the original intention of the code. Please checkout my pull request.

**Comment by xavysp** [comment]
> Hi, I see there is a checkpoint in the checkpoint folder within the DexiNed-Pytorch folder. May I know what is the status of this checkpoint? How is the performance of the PyTorch model in comparison to your TF2 model?
> 
> I'm asking this because I'm seeing quite some mistakes in the code. I have made quite some changes to the code while trying to maintain the original intention of the code. Please checkout my pull request.

Hi @xiankgx,
thanks for your time,  I will check and accept your pull request this Wednesday, sorry I on vacation.
By the way, the official version right now  (for WACV2020 paper) is the one from the TF 1. I am working in the journal version with some changes in the dataset and it will coded by using TF2. and PyTorch.

Cheers!

Xavier

**Comment by xavysp** [comment]
Done! thanks again. Now I am training DexiNed-Pythorch

**Comment by xiankgx** [comment]
I didn't do much other than to do a little of code cleanups and reorganizing here and there. Good luck.
