### ISSUE TITLE
Pretrained Model for Grayscale Images

### ISSUE THREAD

**Issue by GuptaSonam** [xavysp/DexiNed#39]
Hi, 

By any chance do you have the pretrained model for the grayscale images? If yes, can you please share the same?

Thanks
Sonam

**Comment by xavysp** [comment]
> Hi,
> 
> By any chance do you have the pretrained model for the grayscale images? If yes, can you please share the same?
> 
> Thanks
> Sonam

Hi Soman, 
sorry it's interesting but I am afraid that I do not have pretrained checkpoint for grayscale images, I tested CID just copying one channel two times.

Xavier
