### ISSUE TITLE
Question about loss calculation

### ISSUE THREAD

**Issue by Beanocean** [xavysp/DexiNed#45]
https://github.com/xavysp/DexiNed/blob/f22c5369e370ee59b959dfdd096b27c150faf041/DexiNed-Pytorch/main.py#L48
https://github.com/xavysp/DexiNed/blob/f22c5369e370ee59b959dfdd096b27c150faf041/DexiNed-Pytorch/losses.py#L59

Divide the `batch_size` by two times?

**Comment by xavysp** [comment]
> https://github.com/xavysp/DexiNed/blob/f22c5369e370ee59b959dfdd096b27c150faf041/DexiNed-Pytorch/main.py#L48
> 
> 
> https://github.com/xavysp/DexiNed/blob/f22c5369e370ee59b959dfdd096b27c150faf041/DexiNed-Pytorch/losses.py#L59
> 
> Divide the `batch_size` by two times?

Hi @Beanocean, 
thanks for the question I didn't realise the error in L59 losses.py :( because it refer to the sum of the loss from each prediction in DexiNed. Now its fixed.

**Comment by Beanocean** [comment]
@xavysp 
I mean the `batch_size` is divided by two times in the loss calculation: in the `DexiNed-Pytorch/losses.py`, the loss has divide the batch_size, there is no necessary to divide in the `DexiNed-Pytorch/main.py`

**Comment by xavysp** [comment]
> @xavysp
> I mean the `batch_size` is divided by two times in the loss calculation: in the `DexiNed-Pytorch/losses.py`, the loss has divide the batch_size, there is no necessary to divide in the `DexiNed-Pytorch/main.py`

Hi, yes you are right, now it is commented https://github.com/xavysp/DexiNed/blob/9a053dedb725dfd2dd8f1e7301f7a941f61a88b3/DexiNed-Pytorch/main.py#L39

**Comment by Beanocean** [comment]
Thanks a lot for sharing the excellent project.
