### ISSUE TITLE
Different visualization results.

### ISSUE THREAD

**Issue by iconnn-ztw** [xavysp/DexiNed#46]
I used your Pytorch version of the pre-training model to test the same picture. Why did I get inconsistent visual results with the article? Is it because the pytorch training model is different from the TensorFlow training model?I hope to get your advice,thanks!

**Comment by xavysp** [comment]
> I used your Pytorch version of the pre-training model to test the same picture. Why did I get inconsistent visual results with the article? Is it because the pytorch training model is different from the TensorFlow training model?I hope to get your advice,thanks!

Hi, the official version of DexiNed is the implementation in FT1.  The Pytorch version has the final DexiNed model (architecture), however, the parameters settings   are not  done, since I am learning Pytorch, sorry, but it will be ready soon.

**Comment by iconnn-ztw** [comment]
> > I used your Pytorch version of the pre-training model to test the same picture. Why did I get inconsistent visual results with the article? Is it because the pytorch training model is different from the TensorFlow training model?I hope to get your advice,thanks!
> 
> Hi, the official version of DexiNed is the implementation in FT1. The Pytorch version has the final DexiNed model (architecture), however, the parameters settings are not done, since I am learning Pytorch, sorry, but it will be ready soon.

thanks
