### ISSUE TITLE
Pre-trained model in Pytorch Version

### ISSUE THREAD

**Issue by LionXFQ** [xavysp/DexiNed#48]
If you have a pre-trained model for pytorch. Is it convenient for us to download it on Google Drive or Baidu Pan?

**Comment by xavysp** [comment]
Hi @LionXFQ sorry I will update the DexiNed-Pytorch weights soon, I am preparing the DexiNed extension in pytorch version

**Comment by ZhangYuef** [comment]
Also looking forward to the pretrained weights for Pytorch model.

**Comment by Palzer** [comment]
+1 here too.

**Comment by xavysp** [comment]
Sorry guys it will take a little longer, I cannot turn on my PC in the LAB, working remotely.  But hope solve this issue in the coming days and update the DexiNed-Pytorch  checkpoint

Cheers.

Xavier

**Comment by ZhangYuef** [comment]
> Sorry guys it will take a little longer, I cannot turn on my PC in the LAB, working remotely. But hope solve this issue in the coming days and update the DexiNed-Pytorch checkpoint
> 
> Cheers.
> 
> Xavier

I have trained one on BIPED dataset myself. I can share if it may help anyone.

**Comment by anandhu1436** [comment]
> > Sorry guys it will take a little longer, I cannot turn on my PC in the LAB, working remotely. But hope solve this issue in the coming days and update the DexiNed-Pytorch checkpoint
> > Cheers.
> > Xavier
> 
> I have trained one on BIPED dataset myself. I can share if it may help anyone.

please share

**Comment by ZhangYuef** [comment]
This is a checkpoint from epoch 24.  Download link is [here](https://drive.google.com/file/d/1AtrUWWqv6H7J-zIhCLbYJdlhtix34Ij_/view?usp=sharing

Training result is as the following:
![results](https://user-images.githubusercontent.com/20250982/97410306-234b7c80-18bc-11eb-9157-d8c7bb762b8f.png)

**Comment by anandhu1436** [comment]
> This is a checkpoint from epoch 24 trained on BIPED dataset. Download link is [here](https://drive.google.com/file/d/1AtrUWWqv6H7J-zIhCLbYJdlhtix34Ij_/view?usp=sharing).
> 
> Training result is as the following:
> ![results](https://user-images.githubusercontent.com/20250982/97410306-234b7c80-18bc-11eb-9157-d8c7bb762b8f.png)
> 
> Hope this unofficial one can help : )

i have placed this file in checkpoint folder and in 24/ i am getting this error 

 Error(s) in loading state_dict for DexiNed:
	Missing key(s) in state_dict: "block_cat.conv.weight", "block_cat.conv.bias", "block_cat.bn.weight", "block_cat.bn.bias", "block_cat.bn.running_mean", "block_cat.bn.running_var". 
	Unexpected key(s) in state_dict: "block_cat.weight", "block_cat.bias".

**Comment by ZhangYuef** [comment]
> > This is a checkpoint from epoch 24 trained on BIPED dataset. Download link is [here](https://drive.google.com/file/d/1AtrUWWqv6H7J-zIhCLbYJdlhtix34Ij_/view?usp=sharing).
> > Training result is as the following:
> > ![results](https://user-images.githubusercontent.com/20250982/97410306-234b7c80-18bc-11eb-9157-d8c7bb762b8f.png)
> > Hope this unofficial one can help : )
> 
> i have placed this file in checkpoint folder and in 24/ i am getting this error
> 
> Error(s) in loading state_dict for DexiNed:
> Missing key(s) in state_dict: "block_cat.conv.weight", "block_cat.conv.bias", "block_cat.bn.weight", "block_cat.bn.bias", "block_cat.bn.running_mean", "block_cat.bn.running_var".
> Unexpected key(s) in state_dict: "block_cat.weight", "block_cat.bias".

Sorry to forget mention, this checkpoint is trained based on the model of commit a9f6ade. Link from [here](https://github.com/xavysp/DexiNed/commit/a9f6ade958f61995cd6617a949c085a4b2d171cc).

**Comment by soomiles** [comment]
@ZhangYuef Thanks for sharing!
Not sure why this error is popped up like
```
model = DexiNet()
model.load_state_dict(torch.load('24_model.pth'))
```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-68-73ae3f94d42f> in <module>
>       1 model = DexiNet()
> ----> 2 model.load_state_dict(checkpoint)
>       3 print('done')
> 
> /opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
>    1043         if len(error_msgs) > 0:
>    1044             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> -> 1045                                self.__class__.__name__, "\n\t".join(error_msgs)))
>    1046         return _IncompatibleKeys(missing_keys, unexpected_keys)
>    1047 
> 
> RuntimeError: Error(s) in loading state_dict for DexiNet:
> 	size mismatch for dblock_3.denselayer1.conv1.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).
> 	size mismatch for dblock_3.denselayer2.conv1.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, 1]).
> 	size mismatch for dblock_4.denselayer1.conv1.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 1, 1]).
> 	size mismatch for dblock_4.denselayer2.conv1.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
> 	size mismatch for dblock_4.denselayer3.conv1.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
> 	size mismatch for dblock_5.denselayer1.conv1.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
> 	size mismatch for dblock_5.denselayer2.conv1.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
> 	size mismatch for dblock_5.denselayer3.conv1.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 1, 1]).
> 	size mismatch for dblock_6.denselayer1.conv1.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
> 	size mismatch for dblock_6.denselayer2.conv1.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, 1]).
> 	size mismatch for dblock_6.denselayer3.conv1.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, 1]).
> 

But, I changed the first convolution layer of _DenseLayer with kernel=3 and padding=1, then I could successfully load the checkpoint.
```
class _DenseLayer(nn.Sequential):
    def __init__(self, input_features, out_features):
        super(_DenseLayer, self).__init__()

        # self.add_module('relu2', nn.ReLU(inplace=True)),
        self.add_module('conv1', nn.Conv2d(input_features, out_features,
                                           kernel_size=3, stride=1, padding=1, bias=True)),
        self.add_module('norm1', nn.BatchNorm2d(out_features)),
        self.add_module('relu1', nn.ReLU(inplace=True)),
        self.add_module('conv2', nn.Conv2d(out_features, out_features,
                                           kernel_size=3, stride=1, padding=1, bias=True)),
        self.add_module('norm2', nn.BatchNorm2d(out_features))
        # double check the norm1 comment if necessary and put norm after conv2

    def forward(self, x):
        x1, x2 = x
        # maybe I should put here a RELU
        new_features = super(_DenseLayer, self).forward(F.relu(x1))  # F.relu()
        return 0.5 * (new_features + x2), x2
```

**Comment by ZhangYuef** [comment]
Thanks @soomiles  for pointing out ! I did change the model layer as you point out as the official code had dimension error at that time. : )

**Comment by anandhu1436** [comment]
still not working for me , can you share the working  code to anandhuachu5132@gmail.com

**Comment by SoulAttacker** [comment]
Hi, @xavysp I'm sorry to disturb you, but do you have the weight file based on the pytorch version? Or if it’s not convenient for you to release the download link, can you send me an email(soulwalkerilyf@gmail.com)? Thank you!!!   : )

**Comment by xavysp** [comment]
> Hi. Is the official PyTorch pretrained model available yet?

Hi sorry, now you can find the official one.

**Comment by ManuBN786** [comment]
> > Sorry guys it will take a little longer, I cannot turn on my PC in the LAB, working remotely. But hope solve this issue in the coming days and update the DexiNed-Pytorch checkpoint
> > Cheers.
> > Xavier
> 
> I have trained one on BIPED dataset myself. I can share if it may help anyone.

Please do. and send the link. Thanks
