### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by f-sh-f-sh** [xavysp/DexiNed#5]
Hi,

When I try the command: `python run_model.py --image_width=512 --image_height=512`

I get the following error:
```
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node Xpt/conv1_1/Conv2D (defined at /home/DexiNed/models/dexined.py:53) ]]
	 [[node output_6 (defined at /home/DexiNed/models/dexined.py:445) ]]
```

I am using TF 1.13.1. How can I solve this error?

**Comment by xavysp** [comment]
Hi,

sorry I am a little late, but honestly, I cannot find error, as you can see [in this other issue](https://github.com/xavysp/DexiNed/issues/6) it works perfectly. Please make sure you downloaded the checkpoints.

Please let me know if you checked the other issue 

Xavier

**Comment by f-sh-f-sh** [comment]
Thanks for the reply. I downgraded TF to 1.8.0, and then upgraded back to 1.13.1 again, and it worked! I have no idea what has been changed, but now everything is fine.

**Comment by xavysp** [comment]
> Thanks for the reply. I downgraded TF to 1.8.0, and then upgraded back to 1.13.1 again, and it worked! I have no idea what has been changed, but now everything is fine.

Great so I hope enjoy using DexiNed :)

cheers
