### ISSUE TITLE
what is the difference between the pred_a and pred_f?

### ISSUE THREAD

**Issue by MrCrazyCrab** [xavysp/DexiNed#52]
what is the difference between the pred_a and pred_f?

**Comment by g-h-anna** [comment]
I assume pred_a is the "Averaged" output, and pred_f is the "Fused" (see Fig.5 in the article)

**Comment by g-h-anna** [comment]
> what is the difference between the pred_a and pred_f?

I assume pred_a is the "Averaged" output, and pred_f is the "Fused" (see Fig.5 in the article)

**Comment by xavysp** [comment]
> what is the difference between the pred_a and pred_f?

Hi @MrCrazyCrab  as @g-h-anna  says the fused is the in layer fusion of the 6 Dexined outputs and the average is the average :) of the whole of outputs even fused edge-map. For more details, please check the paper ;)

**Comment by za13** [comment]
I was also confused by this. I did read the paper and it was confusing to me. If the pred_f is the "fusion" of the 6 outputs and pred_a is the average, then are they not the same or very similar?

**Comment by g-h-anna** [comment]
> I was also confused by this. I did read the paper and it was confusing to me. If the pred_f is the "fusion" of the 6 outputs and pred_a is the average, then are they not the same or very similar?

As I see (but I hope @xavysp willl correct me if I miss something) they are similar, but not the same. The average is simply average, but in the fusion their weights in taking part in the concatenation is not equal. The 1x1 convolution in the last step may itself introduce non-linearity to it, but in the article of HED (which this works build upon) it is said, that the fusion has weights, which is also learned during the training - so I assume DexiNed also learns the weights for fusion. And if you run the code, you can see the difference in the pred_f and pred_a results.

**Comment by xavysp** [comment]
> > I was also confused by this. I did read the paper and it was confusing to me. If the pred_f is the "fusion" of the 6 outputs and pred_a is the average, then are they not the same or very similar?
> 
> As I see (but I hope @xavysp willl correct me if I miss something) they are similar, but not the same. The average is simply average, but in the fusion their weights in taking part in the concatenation is not equal. The 1x1 convolution in the last step may itself introduce non-linearity to it, but in the article of HED (which this works build upon) it is said, that the fusion has weights, which is also learned during the training - so I assume DexiNed also learns the weights for fusion. And if you run the code, you can see the difference in the pred_f and pred_a results.

@g-h-anna, and yes just like that
