### ISSUE TITLE
predict time

### ISSUE THREAD

**Issue by G-YY** [xavysp/DexiNed#58]
I test my own dataset ,and predict one 1280*720 image consume about 870ms? Is it  right?

**Comment by xavysp** [comment]
Hi, sorry I am a little late, Multicue dataset has the same size and here the time per image:
******** Testing finished in MULTICUE dataset. *****
Average time per image: 0.010431.4 seconds
Time spend in the Dataset: 0.208620.4 seconds (20 images, )

but this repents on your PC, I have tested with a GPU

Cheers,

**Comment by xavysp** [comment]
After ~10 days of inactive , I proceed to close the issue
