### ISSUE TITLE
test result?

### ISSUE THREAD

**Issue by cquirene** [xavysp/DexiNed#6]
when I test the single image, I got the following result, but it is not the expected one.
Is there something wrong with my operation? Thank you! I'm a beginner.
![image](https://user-images.githubusercontent.com/39989750/75958503-58532b00-5ef7-11ea-9a2d-7d31fcebf0e6.png)

**Comment by xavysp** [comment]
Dear friend, just minutes ago I have tested in Lenna image (single image)

Ubuntu 16.04
Tensorflow version: 1.13.1
CUDA Version:  10.0.130
Python: 3.7.3 

Then
1 **git clone https://github.com/xavysp/DexiNed.git DexiNed_tmp**
2  Into DexiNed_tmp folder I have created **checkpoints/DXN_BIPED/train** folders
3 Intro the folder created in 2 (checkpoints/DXN_BIPED/train) I have downloaded the files in
https://drive.google.com/drive/folders/1fLBpOrSXC2VOWUvDtNGyrHcuB2IB-4_D?usp=sharing
4 Do **python run_model.py --image_width=512 --image_height=512**
5 Check the result in **results/DexiNed_BIPED2CLASSIC**. There are some warnings, don’t worries, we are working in TF2.0

4 You can  also run with IDEs, I have tested with Pycharm
see results from Lenna
![lena_std](https://user-images.githubusercontent.com/3678862/76120879-b7499a80-5ff2-11ea-8d67-a35588354ae9.png)

![lena_std](https://user-images.githubusercontent.com/3678862/76120841-a4cf6100-5ff2-11ea-9ef4-b3942b411563.png)
 in DexiNed-a, Dexined-f, respectively.

**Comment by xavysp** [comment]
After waiting 15 days I close the issue
