### ISSUE TITLE
PyTorch TypeError: __init__() got an unexpected keyword argument 'arg' when running main.py

### ISSUE THREAD

**Issue by lucabron** [xavysp/DexiNed#64]
Hello,

I tried to run the default setup in Pytorch on a Google Colab but met an error while running main.py .
My goal is to just get the model to work to understand how it works.

I did this:

1. Mount Drive
2. Clone the repo
3. Install torch opencv-python torchgeometry (the requirements on the PyTorch Readme of DexiNed)
4. Set directory to DexiNed/DexiNed-Pytorch
5. !python main.py
It returns:
```
Number of GPU's available: 1
Pytorch version: 1.8.0+cu101
Traceback (most recent call last):
  File "main.py", line 420, in <module>
    main(args)
  File "main.py", line 361, in main
    test_list=args.test_list, arg=args
TypeError: __init__() got an unexpected keyword argument 'arg'
```
Runnig on CPU generates the same error.

Any tip?

**Comment by dayanyiyiyanda** [comment]
modify  the datasets.py as follow.
TestDataset(Dataset):->__init__() function arg is commented out. make the param to valid
