### ISSUE TITLE
Why "accuracy = metrics.BinaryAccuracy()" is used?

### ISSUE THREAD

**Issue by Optomizer90** [xavysp/DexiNed#72]

**Comment by xavysp** [comment]
Hi sorry for my late response. As you can see in many DL models  there is not accuracy in the training stage, it could be great use a metric for the accuracy. This BinaryAcuracy() is not needed, you can comment it, and the result will be the same.

**Comment by Optomizer90** [comment]
Hi, no issues.

Thank you for the answer. 

Since this is classification problem with highly imbalanced data, Evaluating the model using F1 score will be more appropriate. 

Wanted to know your comments on it? Any code updation (tf2) is possible?

Thank you.

**Comment by xavysp** [comment]
> Hi, no issues.
> 
> Thank you for the answer.
> 
> Since this is classification problem with highly imbalanced data, Evaluating the model using F1 score will be more appropriate.
> 
> Wanted to know your comments on it? Any code updation (tf2) is possible?
> 
> Thank you.

Right, I'll implement it. You'll see how it work

**Comment by Optomizer90** [comment]
> Right, I'll implement it. You'll see how it work

Thank you
