### ISSUE TITLE
Can only run this code by Tensorflow?

### ISSUE THREAD

**Issue by isLucas** [xavysp/DexiNed#79]
First of  all, thanks for the contribution of the author. And I wonder Can I only run this code by Tensorflow? 
Or there is a version of pytorch cause the warning said that you have just updated the last version of DexiNed in Pytorch. The implementation with TF1 will fransfer to the "legacy" dir

**Comment by xavysp** [comment]
> First of all, thanks for the contribution of the author. And I wonder Can I only run this code by Tensorflow?
> Or there is a version of pytorch cause the warning said that you have just updated the last version of DexiNed in Pytorch. The implementation with TF1 will fransfer to the "legacy" dir

Hi,
and sure you can run the TF1 version, just copy the legacy dir. That dir is all you need.
