### ISSUE TITLE
About ODS,OIS,AP

### ISSUE THREAD

**Issue by Dreamerswile** [xavysp/DexiNed#8]
how to achieve the evaluation criterion in your paper, matlab？

**Comment by xavysp** [comment]
Yes in Matlab, I followed the instruction from [RCF](https://github.com/yun-liu/RCF). The difference is just here:
```
edgesNmsMex(tmp_edge,O,1,5,1.03,8)
```
Because the edge-maps predicted from DexiNed are thinner than from RFC or HED

**Comment by Dreamerswile** [comment]
Thank you very much, BSDS500 DataSet contains .mat files , but BIPED do not contain .mat files . How can you solve this problem?

**Comment by xavysp** [comment]
> Thank you very much, BSDS500 DataSet contains .mat files , but BIPED do not contain .mat files . How can you solve this problem?

Hi,
in edgesEvalDir()---from Dollar toolkit change:
ids=dir(fullfile(gtDir,'*.mat')); by ids=dir(fullfile(gtDir,'*.png'));
ant the end the BIPED gt are 0 or 255 (0 or 1).

**Comment by Dreamerswile** [comment]
Could you explain more detail about  "the end the BIPED gt are 0 or 255 (0 or 1)".

**Comment by xavysp** [comment]
> Could you explain more detail about "the end the BIPED gt are 0 or 255 (0 or 1)".

HI 
the GTs in BSDS are more or less 5 so they save into a .mat file. As BIPED has just one GT per image we can save as an image. Before evaluation on Dollars toolkit, for ODS,...AP, the GT is normalizer in a range of 0-1, no matter if the GT comes from .mat or .png, the input for the computation is a 2D matrix.

**Comment by Dreamerswile** [comment]
I got it.But if I only change the edgesEvalDir() function, the load function will report an errror. 
in 56 line    G=load(G); G=G.groundTruth; n=length(G); --- from edgesEvalImg.m 
I think this is because the load function is only suitable for ASCII files whose contents are full rank and all Numbers.And I can't solve the problem.Thank you for your help

**Comment by xavysp** [comment]
> I got it.But if I only change the edgesEvalDir() function, the load function will report an errror.
> in 56 line G=load(G); G=G.groundTruth; n=length(G); --- from edgesEvalImg.m
> I think this is because the load function is only suitable for ASCII files whose contents are full rank and all Numbers.And I can't solve the problem.Thank you for your help

Hi,
I have the code, I could share it, but I need to clean up a lot (I'm a little ashamed), right now I am I little busy. Write to me by email, by the way, I am not a good programmer in Matlab, maybe you can improve it.

**Comment by Dreamerswile** [comment]
Thanks for answering my question.I have sent you an email.

**Comment by Dreamerswile** [comment]
Can you leave your E-mail address？

**Comment by xavysp** [comment]
> Can you leave your E-mail address？

I already sent you an email. But, you may find in my profile. Or write me again please

**Comment by Dreamerswile** [comment]
Thank you very much for your help.But when I run the MATLAB code,I can not find this function edgesEval_x.m.Looking forward to your reply
