### ISSUE TITLE
dexined-boundary vs dexined-edge task?

### ISSUE THREAD

**Issue by weinixuehao** [xavysp/DexiNed#82]
If I need to detect the document contour,  Is the dexined-boundary task the right choice? If it is, how to start this task?
Could you explain the difference between the two tasks?

**Comment by xavysp** [comment]
Hi, sorry I think the banner, does not explain as well as I expected. But edge detection is the detection of all kind of changes in the image intensity. Boundary detection is like a semantic segmentation. For example, in an image of zebra,  for boundary detection is the edge detection of the zebra' body.  Basically, the DexiNed-Boundary, is the model trained in the popular BSDS dataset.

**Comment by weinixuehao** [comment]
According to your explanation, what I should need is boundary detection. I had a task that needs to detect a document or rectangle shape in an image, so how to do it? Is it possible to annotate some images for training?

**Comment by xavysp** [comment]
> According to your explanation, what I should need is boundary detection. I had a task that needs to detect a document or rectangle shape in an image, so how to do it? Is it possible to annotate some images for training?

try both, and see with is better. Sure you can annotate, but at least 100

**Comment by weinixuehao** [comment]
![2_465](https://user-images.githubusercontent.com/17869361/126761770-ab778b68-ebc9-4bbe-83a2-3b3c22dc61bf.png)
![2-600x600](https://user-images.githubusercontent.com/17869361/126761778-06ebd539-b635-4f32-a7fb-25079a662538.png)
![1234](https://user-images.githubusercontent.com/17869361/126761781-b17a561e-1b55-4cfa-8a97-5608525521df.png)
![9418CCDD42654A1D911E7971B068CD8F](https://user-images.githubusercontent.com/17869361/126761784-431f8bf4-1f72-4b17-b8c7-e4d6de9a32f0.png)
![1671626932406_ pic_hd](https://user-images.githubusercontent.com/17869361/126761787-c08a9f26-0662-4c3e-8179-68a27fd47cad.png)
![src=http___am zdmimg com_201508_08_55c4d6e0e3710 jpg_e600 jpg refer=http___am zdmimg](https://user-images.githubusercontent.com/17869361/126761789-c0b9eacf-209e-42b0-93b7-181832063166.png)
![src=http___g-search1 alicdn com_img_bao_uploaded_i2_3168627201_TB2jrnHbbAlyKJjSZFBXXbtiFXa_!!3168627201 jpg_300x300 jpg refer=http___g-search1 alicdn](https://user-images.githubusercontent.com/17869361/126761790-e777d618-2f6d-4bcb-b2f7-40835678c5b8.png)
![src=http___imgsa baidu com_exp_w=500_sign=02cacc61fb246b607b0eb274dbf91a35_ac345982b2b7d0a2b03796afc6ef76094b369a02 jpg refer=http___imgsa baidu](https://user-images.githubusercontent.com/17869361/126761793-c9001953-059c-4bd8-a4fc-6e3a912df2a4.png)
![src=http___imgsa baidu com_exp_w=500_sign=11e9c75b282dd42a5f0901ab333a5b2f_2fdda3cc7cd98d10c72a9e032c3fb80e7bec9002 jpg refer=http___imgsa baidu](https://user-images.githubusercontent.com/17869361/126761796-679c3971-9bf6-40f5-b5a4-ed5d67849565.png)
![src=http___pic ibaotu com_00_11_78_07J888piCVcr jpg-0 jpg!ww700 refer=http___pic ibaotu](https://user-images.githubusercontent.com/17869361/126761802-b5c04d26-b558-4d57-abe1-d3a0ef88aa7e.png)
![vdfg](https://user-images.githubusercontent.com/17869361/126761804-e3f609ed-5a8d-4546-b863-6f573ee67a1b.png)
![2_465](https://user-images.githubusercontent.com/17869361/126761819-1d2e4081-7daa-4faf-a44f-29426b6e0977.jpg)
![2-600x600](https://user-images.githubusercontent.com/17869361/126761821-87659223-0278-4baa-9985-b62c030c2b54.jpeg)
![1234](https://user-images.githubusercontent.com/17869361/126761825-0d3ce5bd-7284-466b-a889-8bffca6d50e9.jpg)
![9418CCDD42654A1D911E7971B068CD8F](https://user-images.githubusercontent.com/17869361/126761828-af3359d5-637c-48ef-86ae-265a6d26c3e2.png)
![1671626932406_ pic_hd](https://user-images.githubusercontent.com/17869361/126761829-3e58a5c3-1099-43c4-befb-6892b8cf4f72.jpg)
![src=http___am zdmimg com_201508_08_55c4d6e0e3710 jpg_e600 jpg refer=http___am zdmimg](https://user-images.githubusercontent.com/17869361/126761834-0c8b7a1b-a6ba-44e5-8ead-01facbeb9ad0.jpeg)
![src=http___g-search1 alicdn com_img_bao_uploaded_i2_3168627201_TB2jrnHbbAlyKJjSZFBXXbtiFXa_!!3168627201 jpg_300x300 jpg refer=http___g-search1 alicdn](https://user-images.githubusercontent.com/17869361/126761837-8b5f94a7-2b67-42e3-914b-e1a8c2d80714.jpeg)
![src=http___imgsa baidu com_exp_w=500_sign=02cacc61fb246b607b0eb274dbf91a35_ac345982b2b7d0a2b03796afc6ef76094b369a02 jpg refer=http___imgsa baidu](https://user-images.githubusercontent.com/17869361/126761839-ad281ac4-f0fc-4e7a-8a6f-57e2001cfb65.jpeg)
![src=http___imgsa baidu com_exp_w=500_sign=11e9c75b282dd42a5f0901ab333a5b2f_2fdda3cc7cd98d10c72a9e032c3fb80e7bec9002 jpg refer=http___imgsa baidu](https://user-images.githubusercontent.com/17869361/126761840-127ee2d6-1634-4e2e-8b0f-3c549261c476.jpeg)
![src=http___pic ibaotu com_00_11_78_07J888piCVcr jpg-0 jpg!ww700 refer=http___pic ibaotu](https://user-images.githubusercontent.com/17869361/126761841-fd425b20-a2ca-4f58-8256-22a340ffb1c5.jpeg)
![vdfg](https://user-images.githubusercontent.com/17869361/126761844-cebe9091-8910-45aa-8125-d13776fd36dd.jpeg)

After I fine-tuned with the pre-trained model, the prediction effect does not seem to be good in complex background.
I guess it’s because this pre-trained model is based on the edge task, so I need to train a model based on boundary tasks? for example, BSDS500 dataset to train? 
Will the result be better than edge tasks?
Could you provide a pre-trained model which bases on the boundary task?

**Comment by g-h-anna** [comment]
> Hi, sorry I think the banner, does not explain as well as I expected. But edge detection is the detection of all kind of changes in the image intensity. Boundary detection is like a semantic segmentation. For example, in an image of zebra, for boundary detection is the edge detection of the zebra' body. Basically, the DexiNed-Boundary, is the model trained in the popular BSDS dataset.

What should I set in code to use if for training he Dexined-Edge instead of Dexined-Boundary?

**Comment by weinixuehao** [comment]
So do I need to train the BSDS dataset for better performance?
