### ISSUE TITLE
How to test it on my single image ?

### ISSUE THREAD

**Issue by yogendra-yatnalkar** [xavysp/DexiNed#87]
First of all, thank you for the amazing work. I wanted to test dexined on my single image. I tried it but I am not able to get that. Can you please tell me how to put exact arguments in: "python main.py ..." to perform model prediction on single image ?

**Comment by ManuBN786** [comment]
same issue here

**Comment by ManuBN786** [comment]
'python main.py --choose_test_data=9' worked for me.
Also you need to set the checkpoints file correctly

**Comment by krummrey** [comment]
Hi @ManuBN786, I was trying to get DexiNed to outline a set of images. I've put the .pth file in checkpoints. Lena is going through. My images aren't. 
I get `AttributeError: 'NoneType' object has no attribute 'shape'` [Full error](https://pastebin.com/Uq1MS1vQ)

Do the images need to be in a special format? 
Or can I use it only on 512x512 images? 
Or do all sides need to be divisible by 16?

I'd love to have a way to dump a bunch of images, start a script and get the corresponding outlines at the same resolution as the input. Is that possible?

**Comment by yogendra-yatnalkar** [comment]
@ManuBN786 Thanks a lot for your help.
