### ISSUE TITLE
--use_dataset not available as per README

### ISSUE THREAD

**Issue by lukegriffiths** [xavysp/DexiNed#95]
I'm trying to run the code in test mode using:

`python main.py --choose_test_data=-1`

The test dataset is indeed ORIGINAL, but the code is still looking for `train_inf['train_list']` for the train dataset (which I left as default BSDS) and I can't see any `--use_dataset` to set to `False `as indicated in the README.

I'm new to this, sorry if it is obvious. Thanks in advance!

**Comment by xavysp** [comment]
> I'm trying to run the code in test mode using:
> 
> `python main.py --choose_test_data=-1`
> 
> The test dataset is indeed ORIGINAL, but the code is still looking for `train_inf['train_list']` for the train dataset (which I left as default BSDS) and I can't see any `--use_dataset` to set to `False `as indicated in the README.
> 
> I'm new to this, sorry if it is obvious. Thanks in advance!

Hi @lukegriffiths, sorry  now I have updated README please check.
