### ISSUE TITLE
Length of data samples wrongly calculated

### ISSUE THREAD

**Issue by Adalsteinnjons** [xavysp/DexiNed#98]
Hi there and thank you for this great project. 
When testing the model I noticed the length of the dataset is being calculated not over all images in the dataset but over the array [[images],[labels]] and therefore always returns the number 2.
This caused me issues as I was trying to test with the Lena sample. When I tested it with only Lena in the data folder I got an error. When I added 2 images in there it worked, but when there are more than 2 images in the data folder, only the first 2 were being processed.

How it is currently (always returns 2, no matter how many images in data folder):
https://github.com/xavysp/DexiNed/blob/3ad5f087f7d63ff43174fc0fb429792350338748/datasets.py#L229-L230

It should be: 
```python
def __len__(self):
        return len(self.data_index[0])
```

**Comment by xavysp** [comment]
Hi @Adalsteinnjons, thanks, I also have noticed that error a couple of days ago, in the last commit It will be corrected.
